Fix for RESTX-42: No more hard-wired component names in a Python source file. Instead, we now have small 'manifest' files (not in XML) for each component. The server reads those files at start and dynamically imports the necessary component classes.
The restxctl script is updated to now just create a manifest file.

Also, it's possible to now 'create' a new component for which we have the
source file already. In that case, only the manifest is created, the source
template file is NOT put in place of the old component code.

diff --git a/bin/frags/_ctl_frg b/bin/frags/_ctl_frg
--- a/bin/frags/_ctl_frg
+++ b/bin/frags/_ctl_frg
@@ -8,7 +8,9 @@
 # component templates for the various languages.
 #
 
-COMPONENT_LIST="src/python/restx_components_list/__init__.py"
+COMP_CONF_DIR=conf/components
+COMP_CONF_EXT=.cmfs
+
 LANGUAGES=
 
 function restx_help
@@ -67,7 +69,7 @@ function start_restx
     if [ $? == 0 ]; then
         sleep 4
     else
-        exit $?
+        exit 1 
     fi
 }
 
@@ -134,15 +136,27 @@ function create_component
     fi
 
     # Check if we have a component with the suggested name already
-    chk=`grep " import $name#" "$RESTX_HOME"/"$COMPONENT_LIST"`
-    if [ ! -z "$chk" ]; then
+    conf_file="$RESTX_HOME/$COMP_CONF_DIR/$name$COMP_CONF_EXT"
+    if [ -f "$conf_file" ]; then
         echo "A component with name '$name' exists already."
         exit 1
     fi
 
+    # Start creating the config file
+    echo "ENABLED = yes" > $conf_file
+    echo "cname   = $name" >> $conf_file
+    echo "lang    = $language" >> $conf_file
+
+
     # Call the language specific placement script
-    $RESTX_HOME/languages/$language/util/placement $1 $RESTX_HOME "$COMPONENT_LIST"
-    exit $?
+    $RESTX_HOME/languages/$language/util/placement $1 $RESTX_HOME "$conf_file"
+    if [ $? == 0 ]; then
+        exit 0
+    else
+        echo "Creation of new component failed..."
+        rm $conf_file
+        exit 1
+    fi
 }
 
 
diff --git a/bin/generic_placement b/bin/generic_placement
--- a/bin/generic_placement
+++ b/bin/generic_placement
@@ -31,7 +31,7 @@
 # $5:  source directory of template
 # $6:  $RESTX_SRC directory (development directory for that language)
 # $7:  name of the sample component (usually 'SampleComponent')
-# $8:  location of the __init__.py script where the component import needs to be added
+# $8:  location of the component's partially created config file
 # $9:  potential suffix to the module name for import
 # $10: flag indicating whether this language requires compilation or not
 #
@@ -43,7 +43,7 @@ LANGUAGE_ENDING="$4"
 LANGUAGES_SRC="$5"
 RESTX_SRC="$6"
 SAMPLE_COMPONENT_NAME="$7"
-COMPONENT_LIST="$8"
+COMPONENT_CONF_FILE="$8"
 MODULE_NAME_SUFFIX="$9"
 COMPILATION_NEEDED="${10}"
 
@@ -100,38 +100,40 @@ newfile="$newpath/$filename"
 #
 # Check whether a component with that name exists already
 #
-if [ -f "$newfile" ]; then
-    echo "A component with that name already exists in the development directory: $newfile"
-    echo
-    exit 1
+if [ -f "$RESTX_HOME/$newfile" ]; then
+    echo "A component with that name already exists in the development directory: $RESTX_HOME/$newfile"
+    echo "This component file will not be over-written."
+    echo "But a manifest file does not exist yet. Only creating manifest file."
+else
+
+    #
+    # Copy the sample component in the right place
+    #
+
+    cp "$LANGUAGES_SRC/$fullpath" "$RESTX_HOME/$newfile"
+    if [ $? == 1 ]; then
+        echo "Cannot copy sample component to $RESTX_HOME/$newfile..."
+        echo
+        exit 1
+    fi
+
+    #
+    # Change the name in the file
+    #
+    sed --in-place=.orig s/$SAMPLE_COMPONENT_NAME/$name/ $RESTX_HOME/$newfile
+    if [ $? == 1 ]; then
+        echo "Failed to modify name new component template to $name"
+        echo
+        exit 1
+    fi
+    rm "$newfile".orig
 fi
 
 #
-# Copy the sample component in the right place
+# Finalize the manifest file for the component
 #
-
-cp "$LANGUAGES_SRC/$fullpath" "$newfile"
-if [ $? == 1 ]; then
-    echo "Cannot copy sample component to $newfile..."
-    echo
-    exit 1
-fi
-
-#
-# Change the name in the file
-#
-sed --in-place=.orig s/$SAMPLE_COMPONENT_NAME/$name/ $newfile
-if [ $? == 1 ]; then
-    echo "Failed to modify name new component template to $name"
-    echo
-    exit 1
-fi
-rm "$newfile".orig
-
-#
-# Add an import statement to the components-list Python file
-#
-echo "from $modulename import $name#$LANGUAGE" >> $RESTX_HOME/$COMPONENT_LIST
+echo "module  = $modulename" >> $COMPONENT_CONF_FILE
+echo "path    = $newfile" >> $COMPONENT_CONF_FILE
 
 echo -e "Created new component: $newfile\n"
 
